### ISSUE TITLE
Predict single observation

### ISSUE THREAD

**Issue by rbnx** [pablrod/p5-AI-XGBoost#1]
I am trying to predict observations one by one this is what I have tried 

```
for my $d (@$data) {
    my $in = $d->{data} ;
    my $x;

    AI::XGBoost::CAPI::RAW::XGDMatrixCreateFromMat(
        \$in, 1, 8, $MISSING_VAL, \$x
    );

    my($len,$out);
    AI::XGBoost::CAPI::RAW::XGBoosterPredict($booster, $x, 0, 0,\$len,\$out);
    my $predictions = $ffi->cast(opaque => "float[$len]", $out);
    say $predictions->[0];
}
```

but all the outputs are the same

> 0.935762047767639
> 0.935762047767639
> 0.935762047767639
> 0.935762047767639
> 0.935762047767639
> 0.935762047767639
> 0.935762047767639
> 0.935762047767639

in the code snippet `$in` is an array ref with 8 elements 
e.g: `[ '1', '2', '1', '1', '45', '1', '2888', '0' ]`

I already double checked that I'm getting different elements each iteration but the output is always the same.

Any advice? 
Thanks!

**Comment by pablrod** [comment]
It's a bug!! Thank you for pointing this out!

The type mapping is wrong for function `AI::XGBoost::CAPI::RAW::XGDMatrixCreateFromMat`. The correct type mapping is `float[]` instead of `float*`. 

The intended use is:
```perl
AI::XGBoost::CAPI::RAW::XGDMatrixCreateFromMat(
    $in, # This is already a reference (an array reference) 
    1, 8, $MISSING_VAL, \$x 
);
```

I'm going to fix this right now!

**Comment by pablrod** [comment]
I've realized that there are more functions with this bug (eg.: `XGBoosterBoostOneIter`, `XGDMatrixCreateFromCSC`, `XGDMatrixCreateFromCSR`...)

I'm going to fix all these functions before making a new release to [CPAN](https://metacpan.org) this weekend.

Meanwhile please check the fix and don't hesitate to contribute with suggestions, issues, pull requests...

**Comment by rbnx** [comment]
Thanks for fixing this! I will test it again today

**Comment by pablrod** [comment]
All float arrays type mappings are fixed now. I've just released a new version to CPAN with the fix.

I'm going to make a full perl wrapper, Moose based (see [ROADMAP](https://metacpan.org/pod/AI::XGBoost#ROADMAP)), but if you miss something I can add it before other features, just open an issue.
Thank you!
